// <auto-generated />
using System;
using Control_Transacciones_BD3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Control_Transacciones_BD3.Migrations
{
    [DbContext(typeof(ModeloDatos2Context))]
    partial class ModeloDatos2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Control_Transacciones_BD3.Models.GeneroMusical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fechaRegistro");

                    b.Property<string>("NombreGeneroMusical")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombreGeneroMusical");

                    b.HasKey("Id")
                        .HasName("PK__genero_m__3213E83F6F3BDC0C");

                    b.ToTable("genero_musical", (string)null);
                });

            modelBuilder.Entity("Control_Transacciones_BD3.Models.Nacionalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fechaRegistro");

                    b.Property<string>("NombreNacionalidad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombreNacionalidad");

                    b.HasKey("Id")
                        .HasName("PK__nacional__3213E83F6E0D322E");

                    b.ToTable("nacionalidad", (string)null);
                });

            modelBuilder.Entity("Control_Transacciones_BD3.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Estado")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fechaNacimiento");

                    b.Property<int?>("IdGeneroMusical")
                        .HasColumnType("int")
                        .HasColumnName("idGeneroMusical");

                    b.Property<int?>("IdNacionalidad")
                        .HasColumnType("int")
                        .HasColumnName("idNacionalidad");

                    b.Property<string>("Nombres")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PK__persona__3213E83F73C2931A");

                    b.HasIndex("IdGeneroMusical");

                    b.HasIndex("IdNacionalidad");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("Control_Transacciones_BD3.Models.Persona", b =>
                {
                    b.HasOne("Control_Transacciones_BD3.Models.GeneroMusical", "IdGeneroMusicalNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdGeneroMusical")
                        .HasConstraintName("FK__persona__idGener__3B75D760");

                    b.HasOne("Control_Transacciones_BD3.Models.Nacionalidad", "IdNacionalidadNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdNacionalidad")
                        .HasConstraintName("FK__persona__idNacio__3C69FB99");

                    b.Navigation("IdGeneroMusicalNavigation");

                    b.Navigation("IdNacionalidadNavigation");
                });

            modelBuilder.Entity("Control_Transacciones_BD3.Models.GeneroMusical", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Control_Transacciones_BD3.Models.Nacionalidad", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
